# Default values for llamagpt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ui:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
    internalPort: 3000
  image:
    repository: ghcr.io/getumbrel/llama-gpt-ui
    tag: 1.0.1
    pullPolicy: IfNotPresent
  affinity: {}

api:
  defaultmodel: /models/llama-2-7b-chat.bin
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  image:
    repository: ghcr.io/getumbrel/llama-gpt-api
    tag: 1.0.1
    pullPolicy: IfNotPresent
  affinity: {}
